### ISSUE TITLE
User's "fullname" should be optional

### ISSUE THREAD

**Issue by njam** [floscha/tinycards-python-api#15]
The "fullname" field is optional on tinycards. If not set it will be empty in the API response.

For example [this line in`rest_api.py`](https://github.com/floscha/tinycards-python-api/blob/8c7ca2b3ecfc53d8c313283aa5f34412fa61b77b/tinycards/networking/rest_api.py#L60) fails if no fullname is set.

**Comment by floscha** [comment]
Solved with #16. Thanks again!
