### ISSUE TITLE
Functionality for Private Decks

### ISSUE THREAD

**Issue by jamwil** [floscha/tinycards-python-api#32]
Does the API provide an interface for accessing Private or Draft decks?

**Comment by floscha** [comment]
Hi @jamwil, sorry for the late response but could you check if this issue still exists. I tried to reproduce it but everything works as expected for me.

**Comment by jamwil** [comment]
Sorry for the delay! I just tried starting from scratch with a fresh environment and the issue seems to persist. Steps to reproduce:
```
Logged in as 'jamwil' (jamwil@gmail.com)
>>> client
<tinycards.client.tinycards.Tinycards object at 0x7ff6a6f47940>
>>> client.get_user_info()
<tinycards.model.user.User object at 0x7ff6a5a4b940>
>>> all_decks = client.get_decks()
>>> [deck.title for deck in all_decks]
[]
```
I removed the line initialising the class, but the login appears to work perfectly. Now, if I login to Tinycards and navigate to the same API endpoint that `get_decks()` uses, I get my decks.
```
{
  "decks": [
    {
      "averageFreshness": 1.647311991802659e-19, 
      "awardEligible": false, 
      "blacklisted": null, 
      "blacklistedQuestionTypes": [
        [
          "ASSISTED_PRODUCTION", 
          "PRODUCTION"
        ], 
        [
          "ASSISTED_PRODUCTION", 
          "PRODUCTION"
        ]
      ], 
      "blacklistedSideIndices": [], 
      "cardCount": 19, 
...
```
I'm not sure what is missing. I'm sure it's something trivial. For reference, the deck's visibility is set to Only Me, however the problem seems to persist if I set it be viewable to those with a link.

I'll keep poking around.

**Comment by floscha** [comment]
Sorry for the late response again. I realized that the fix for the JWT issue was not yet released on PyPI, so I pushed a new version today.

Now, if you run `pip install --upgrade tinycards`, it should hopefully work as intended.

**Comment by jamwil** [comment]
I haven't had a chance to try this but I'll close the issue for now. If this doesn't fix it, I must be missing something on my end.
