### ISSUE TITLE
ImportError: No module named networking.rest_api

### ISSUE THREAD

**Issue by tomasstranik** [floscha/tinycards-python-api#36]
Just install it with pip and try the import tinycards command.
Failed with "ImportError: No module named networking.rest_api"

Log below:

Looking in indexes: https://pypi.python.org/simple, https://pypi.apple.com/simple
Collecting tinycards
  Downloading https://files.pythonhosted.org/packages/53/c3/f6be435a81618a19a5f6427fc2d4849dabac497412a510b834444ffc52f0/tinycards-0.23.tar.gz
Collecting requests (from tinycards)
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 3.5MB/s 
Collecting retrying==1.3.3 (from tinycards)
  Downloading https://files.pythonhosted.org/packages/44/ef/beae4b4ef80902f22e3af073397f079c96969c69b2c7d52a57ea9ae61c9d/retrying-1.3.3.tar.gz
Collecting idna<2.9,>=2.5 (from requests->tinycards)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 17.3MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests->tinycards)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 6.3MB/s 
Collecting certifi>=2017.4.17 (from requests->tinycards)
  Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 7.0MB/s 
Collecting urllib3<1.25,>=1.21.1 (from requests->tinycards)
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 19.5MB/s 
Requirement already satisfied: six>=1.7.0 in /Library/Python/2.7/site-packages (from retrying==1.3.3->tinycards) (1.11.0)
Installing collected packages: idna, chardet, certifi, urllib3, requests, retrying, tinycards
  Running setup.py install for retrying ... done
  Running setup.py install for tinycards ... done
Successfully installed certifi-2018.11.29 chardet-3.0.4 idna-2.8 requests-2.21.0 retrying-1.3.3 tinycards-0.23 urllib3-1.24.1
$ python
Python 2.7.10
Type "help", "copyright", "credits" or "license" for more information.
>>> import tinycards
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/tinycards/__init__.py", line 1, in <module>
    from tinycards.client import Tinycards
  File "/Library/Python/2.7/site-packages/tinycards/client/__init__.py", line 1, in <module>
    from .tinycards import Tinycards
  File "/Library/Python/2.7/site-packages/tinycards/client/tinycards.py", line 1, in <module>
    from tinycards.networking.rest_api import RestApi
ImportError: No module named networking.rest_api

**Comment by tomasstranik** [comment]
Any ideas?

**Comment by floscha** [comment]
Hey @tomasstranik, sorry for the late response but Christmas preparations keep me busy these days . It seems like you're using Python 2.7, while the Tinycards API is only tested for Python 3. Do you have any specific reason for using Python 2.7? Otherwise, I'd recommend going with Python 3, since more and more libraries phase-out Python 2 support these days.

**Comment by floscha** [comment]
Since Tinycards has been [disabled by Duolingo](https://support.duolingo.com/hc/en-us/articles/360043909772-UPDATE-Tinycards-Announcement) on September 1, 2020, this repository will no longer be maintained.
