### ISSUE TITLE
Create Deck

### ISSUE THREAD

**Issue by RodrigoBen** [floscha/tinycards-python-api#39]
Exists some function to create a new deck? If exists how to use this?

**Comment by floscha** [comment]
Hi @RodrigoBen 

Sorry for the late reply but yes, you can create new decks like so:
```python
import tinycards
client  = tinycards.Tinycards()

new_deck = tinycards.Deck('Deck Title')
client.create_deck(new_deck)
```

**Comment by RodrigoBen** [comment]
Hi @floscha 
Don't worry, 
Thank you very much.

**Comment by RodrigoBen** [comment]
Hi @floscha 
How are you,
I can't create a new Deck because 'tinycards' has not an attribute 'Deck'.

**Comment by floscha** [comment]
Hi @RodrigoBen 

My bad, it should be
```python
new_deck = tinycards.model.Deck('Deck Title')
```

**Comment by RodrigoBen** [comment]
Hi @floscha 
Thanks very much, it's working

**Comment by floscha** [comment]
Glad I could help :)

**Comment by RodrigoBen** [comment]
Hello @floscha 

I had an error when I try to create a new Deck, my code stop work(Lastly 15 ago was ok), the tinycard version is 0.25. I validated the result print(new_deck) on JSONLint and there had an error. Follow the Code, error and JSON Validated atachement:


**my code:**
'def criarDeck(nome, cards):
        cards=json.loads(leArquivo(cards))
        print("Criando Decks\nNome do Deck a ser Criado:\t"+nome)
        auth=json.loads(leArquivo("credenciais.json"))
        client=tinycards.Tinycards(auth['email'], auth['senha'])
        new_deck=tinycards.model.Deck(nome)
        for i in cards:
                card_touple=(i["frente"], i["verso"])
                new_deck.add_card(card_touple)
        print("\n\n\n\n\n\n")
        print(new_deck)
        print("\n\n\n\n\n\n\nCriado com sucesso")
        client.create_deck(new_deck)'

**My error:**


' File "MyLocation\Python\Python37-32\lib\site-packages\tinycards\client\tinycards.py", line 154, in create_deck
    created_deck = self.data_source.create_deck(deck)
  File "MyLocation\Python\Python37-32\lib\site-packages\tinycards\networking\rest_api.py", line 245, in create_deck
    json_data = r.json()
  File "MyLocation\Python\Python37-32\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "MyLocation\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "MyLocation\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "MyLocation\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)'

**Print of new_deck**
{'id': None, 'user_id': None, 'creation_timestamp': None, 'title': 'Testando Um Dois Tres', 'description': None, 'cards': [{'id': 'd7ef5942-7d80-436f-aa3c-4d3da4167816', 'user_id': None, 'creation_timestamp': 1552564311000, 'front': {'side_id': '3dbdc5a8-b476-47a7-8bf2-126559e01211', 'user_id': None, 'concepts': [{'fact': {'id': '8c68bb3a5e1b4286a6f4fb35b12b5d74', 'text': 'Eu estava cavando no jardim.', 'type': 'TEXT', 'image_url': None, 'tts_url': None}, 'user_id': None,
'id': '977cab92-04c4-44d9-bc61-7c505b616259', 'creation_timestamp': 1552564311.820238, 'update_timestamp': 1552564311.820238}]}, 'back': {'side_id': 'a9c3b185-a32f-449c-81f8-ced70c95fee9', 'user_id': None, 'concepts': [{'fact': {'id': '012ae287961d434e95d01cae8df31dea', 'text': 'I was digging in the garden.', 'type': 'TEXT', 'image_url': None, 'tts_url': None}, 'user_id': None, 'id': 'd9242924-016c-4312-9be6-a716da5b929d', 'creation_timestamp': 1552564311.820238, 'update_timestamp': 1552564311.820238}]}}, {'id': 'c3b9229d-4e25-4bcf-b539-cdd2a0b479ee', 'user_id': None, 'creation_timestamp': 1552564311000, 'front': {'side_id': 'e813d614-4eb3-4d4f-8db0-74320b0edeb9', 'user_id': None, 'concepts': [{'fact': {'id': '34dc6fd7db91408a87d83b036a5eb74d', 'text': 'Ela acordou esticando-se preguiçosamente.', 'type': 'TEXT', 'image_url': None, 'tts_url': None}, 'user_id': None, 'id': '3c970b7b-67bf-4c0d-87c0-89e551e6c5c9', 'creation_timestamp': 1552564311.820238, 'update_timestamp': 1552564311.820238}]}, 'back': {'side_id': 'c5f144b2-bf01-4a24-9534-4b6d433d3b10', 'user_id': None, 'concepts': [{'fact': {'id':
'da58b047994141a5b7dd1fc85624a5b2', 'text': 'She awoke up stretching lazily.', 'type': 'TEXT', 'image_url': None, 'tts_url': None}, 'user_id': None, 'id': '2503931a-ac02-43ab-9573-e9eeee2abf70', 'creation_timestamp': 1552564311.820238, 'update_timestamp': 1552564311.820238}]}}, {'id': 'cc70d4dc-5c7c-465e-90f8-3734833ad39b', 'user_id': None, 'creation_timestamp': 1552564311000, 'front': {'side_id': '47058dea-c2cc-4c64-9565-98c039e363b2', 'user_id': None, 'concepts': [{'fact': {'id': '1662ed97055b4b8683b045d506f96396', 'text': 'O urso tem uma toca na árvore.', 'type': 'TEXT', 'image_url': None, 'tts_url': None}, 'user_id': None, 'id': '086c5f6d-027e-4eed-b5bf-ce3608ae8867', 'creation_timestamp': 1552564311.8212364, 'update_timestamp': 1552564311.8212364}]}, 'back': {'side_id': '5ecc23ab-069d-4abc-8a77-80a6067e3900', 'user_id': None, 'concepts': [{'fact': {'id': 'af9f634715024b0d92edf4b2930c130a', 'text': 'The bear have a den in a three.', 'type': 'TEXT', 'image_url': None, 'tts_url': None}, 'user_id': None, 'id': '1b3d5260-a146-47be-9d8c-71e18cc8f0e7', 'creation_timestamp': 1552564311.8216066, 'update_timestamp': 1552564311.8216066}]}}, {'id': 'e5c5db4e-8e58-48e3-ac97-5184f5d19473', 'user_id': None, 'creation_timestamp': 1552564311000, 'front': {'side_id': '4307c983-52af-464c-8a21-03a32bd780fa', 'user_id': None, 'concepts': [{'fact': {'id': '691276c901d2401783c23f0867337b39', 'text': 'Ela ainda o atormentava.', 'type': 'TEXT', 'image_url': None, 'tts_url': None}, 'user_id': None, 'id': '5bed2223-8a60-4753-8f02-86da658adf6f', 'creation_timestamp': 1552564311.8216066, 'update_timestamp': 1552564311.8216066}]}, 'back': {'side_id': 'b36a0b3d-ffc2-4827-800d-ddadc4f9db34', 'user_id': None, 'concepts': [{'fact': {'id': '007e08f27f2641e197161598e826dcdc', 'text': 'She still tantalized him.', 'type': 'TEXT', 'image_url': None, 'tts_url': None}, 'user_id': None, 'id': '88e0544d-b0a2-4dbd-9310-31b7ee17182c', 'creation_timestamp': 1552564311.8222315, 'update_timestamp': 1552564311.8222315}]}}, {'id': '1bb084af-f40b-49c9-bfa1-b2eb0684f33f', 'user_id': None, 'creation_timestamp': 1552564311000, 'front': {'side_id': 'bd969ee7-9412-4087-8256-4b08bf792962', 'user_id': None, 'concepts': [{'fact': {'id': '67cc73f5214f46c98ecee100c9a516ae', 'text': 'Eu não consigo aguentar vendo você chorar.', 'type': 'TEXT', 'image_url': None, 'tts_url': None}, 'user_id': None, 'id': '628b689b-95cb-4993-afc5-aab7821c16bd', 'creation_timestamp': 1552564311.8222315, 'update_timestamp': 1552564311.8222315}]}, 'back': {'side_id': 'a1805ccb-e587-4083-bfe7-2e31eff23ac4', 'user_id': None, 'concepts': [{'fact': {'id': '00b995f8ea0f4d929c7f890c2346f08b', 'text': "I can't bear seeing you cry.", 'type': 'TEXT', 'image_url': None, 'tts_url': None}, 'user_id': None, 'id': '275d03b4-ebc7-4873-9a59-e7e1a3b7b29e', 'creation_timestamp': 1552564311.8222315, 'update_timestamp': 1552564311.8222315}]}}, {'id': '1d75d057-b01e-4597-bb61-8ed07900b843', 'user_id': None, 'creation_timestamp': 1552564311000, 'front': {'side_id': 'd2602c3b-d8af-4adb-9c0e-41e50cc17094', 'user_id': None, 'concepts': [{'fact': {'id': 'edf0686ba9ef4f0b911bf0da95396b89', 'text': 'Irene foi aperfeiçoando seu ofício nos últimos 20 anos.', 'type': 'TEXT', 'image_url': None, 'tts_url': None}, 'user_id': None, 'id': '919ae1f3-f1cf-4d2c-b314-4516b8845358', 'creation_timestamp': 1552564311.8222315, 'update_timestamp': 1552564311.8222315}]}, 'back': {'side_id': 'ed104cc5-fde5-4ad8-9484-e32b64c327de', 'user_id': None, 'concepts': [{'fact': {'id': '5872280957bc4b0eaf44abfaf7c13137', 'text': 'Irene has been honing her craft for the past 20 years.', 'type': 'TEXT', 'image_url': None, 'tts_url': None}, 'user_id': None, 'id': 'a4dd5c28-6417-4e01-8d26-0c0443ae97e1', 'creation_timestamp': 1552564311.8222315, 'update_timestamp': 1552564311.8222315}]}}, {'id': '13a7264f-b267-4b6f-843f-3e882e405044', 'user_id': None, 'creation_timestamp': 1552564311000, 'front': {'side_id': 'c6fe9571-88c2-434d-a39e-21227c2798f5', 'user_id': None, 'concepts': [{'fact': {'id': 'e7fe7a4c936b433f9652bf907f5f388b', 'text': 'Ele passeava na escola.', 'type': 'TEXT', 'image_url': None,
'tts_url': None}, 'user_id': None, 'id': '71791f39-e6fa-415c-978d-51832ec2b4c2', 'creation_timestamp': 1552564311.8222315, 'update_timestamp': 1552564311.8222315}]}, 'back': {'side_id': '53af0476-230d-45bb-b865-819d6a8c479a', 'user_id': None, 'concepts': [{'fact': {'id': '765501f8cc004cd9a9b7137404458166', 'text': 'He sauntered into school.', 'type': 'TEXT', 'image_url': None, 'tts_url': None}, 'user_id': None, 'id': '418e6f2f-295d-4103-815f-863f4ed1c615', 'creation_timestamp': 1552564311.8232296, 'update_timestamp': 1552564311.8232296}]}}, {'id': '9f702a85-0b11-4e8e-902b-24f8b8a9dd77', 'user_id': None, 'creation_timestamp': 1552564311000, 'front': {'side_id': '81df0c12-33b3-4fbc-8046-fffb9a5919de', 'user_id': None, 'concepts': [{'fact': {'id': '9000f0ced6624cd0855792fb4217869b', 'text': 'Um livro recheado de informações.', 'type': 'TEXT', 'image_url': None, 'tts_url': None}, 'user_id': None, 'id': 'ec6daf72-9817-4236-97ce-90fba7551067', 'creation_timestamp': 1552564311.8232296, 'update_timestamp': 1552564311.8232296}]}, 'back': {'side_id': 'a655d4fb-8b05-4bde-8229-1f24f5cbd6bc', 'user_id': None, 'concepts': [{'fact': {'id': 'ec6c6de33c2e4202a7a2cc699bbad835', 'text': 'A book stuffed with informations.', 'type': 'TEXT', 'image_url': None, 'tts_url': None}, 'user_id': None, 'id': '0351c0e3-5de4-4bed-a1b2-9e69db671fd4', 'creation_timestamp': 1552564311.8232296, 'update_timestamp': 1552564311.8232296}]}}]}



Thanks

**Comment by floscha** [comment]
Hi @RodrigoBen 

I get the same error when running your code with the latest version. The problem is that apparently the `create_deck()` method only works for empty decks at the moment.

However, for now, the following workaround should work for you:
```python
def criarDeck(nome, cards):
        cards=json.loads(leArquivo(cards))
        print("Criando Decks\nNome do Deck a ser Criado:\t"+nome)
        auth=json.loads(leArquivo("credenciais.json"))
        client=tinycards.Tinycards(auth['email'], auth['senha'])

        # First create the empty deck
        new_deck=client.create_deck(tinycards.model.Deck(nome))
        
        for i in cards:
                card_touple=(i["frente"], i["verso"])
                new_deck.add_card(card_touple)
        print("\n\n\n\n\n\n")
        print(new_deck)
        print("\n\n\n\n\n\n\nCriado com sucesso")

        # Then update the deck after adding your cards
        client.update_deck(new_deck)
```

**Comment by RodrigoBen** [comment]
Hi @floscha, 
Thanks, it's working.
