### ISSUE TITLE
Feature request: support deck configuration options

### ISSUE THREAD

**Issue by marccarre** [floscha/tinycards-python-api#50]
### Why?

This would be useful to configure the user experience when decks are used to learn & test one-self. In particular,

- decks to learn languages using special characters may be painful to use if typing is enabled ;
- decks with "secondary" facts (e.g. sample sentences) on the back of the cards may want to only test using the front values (since Tinycards doesn't allow one to label these "secondary" facts as "not used for tests" [yet](https://forum.duolingo.com/comment/22295281/Adding-facts-to-TinyCards)).

#### Default:

- Request:

    ```json
    {
      "description": "Test description",
      "blacklistedSideIndices": "[]",
      "blacklistedQuestionTypes": "[]",
      "gradingModes": "[]",
      "fromLanguage": "en",
      "ttsLanguages": "[]",
      "private": false,
      "shareable": false
    }
    ```

  N.B.: complex JSON values are stringified.

- Response:

    ```json
    {
      "description": "Test description",
      "blacklistedSideIndices": [],
      "blacklistedQuestionTypes": [],
      "gradingModes": [],
      "fromLanguage": "en",
      "ttsLanguages": [],
      "private": false,
      "shareable": false
    }
    ```

#### Shareable only via link

- Request:

    ```json
    {
      "private": true,
      "shareable": true
    }
    ```

- Response:

    ```json
    {
      "compactId": "LEbBQJFU",
      "slug": "test",
      "private": true,
      "shareable": true
    }
    ```

  The `compactId` and `slug` fields can then be used to generate an URL of this form: https://tiny.cards/decks/LEbBQJFU/test, i.e.: `https://tiny.cards/decks/<compactId>/<slug>`.

#### Test knowledge with "front" values only

- Request:

    ```json
    {
      "blacklistedSideIndices": "[1]"
    }
    ```

- Response:

    ```json
    {
      "blacklistedSideIndices": [
        1
      ]
    }
    ```

#### Test knowledge with "back" values only

- Request:

    ```json
    {
      "blacklistedSideIndices": "[0]"
    }
    ```

- Response:

    ```json
    {
      "blacklistedSideIndices": [
        0
      ]
    }
    ```

#### Test without typing answers

- Request:

    ```json
    {
      "blacklistedQuestionTypes": "[[\"ASSISTED_PRODUCTION\",\"PRODUCTION\"],[\"ASSISTED_PRODUCTION\",\"PRODUCTION\"]]"
    }
    ```

- Response:

    ```json
    {
      "blacklistedQuestionTypes": [
        [
          "ASSISTED_PRODUCTION",
          "PRODUCTION"
        ],
        [
          "ASSISTED_PRODUCTION",
          "PRODUCTION"
        ]
      ]
    }
    ```

#### Do not accept typos

- Request:

    ```json
    {
      "blacklistedQuestionTypes": "[]",
      "gradingModes": "[\"NO_TYPOS\",\"NO_TYPOS\"]"
    }
    ```

- Response:

    ```json
    {
      "blacklistedQuestionTypes": [],
      "gradingModes": [
        "NO_TYPOS",
        "NO_TYPOS"
      ]
    }
    ```

#### Text-to-speech

- Request:

    ```json
    {
      "ttsLanguages": "[\"en\",\"ja\"]"
    }
    ```

- Response:

    ```json
    {
      "ttsLanguages": [
        "en",
        "ja"
      ]
    }
    ```

N.B.: first language is the front of the cards, second language in the back of the cards.

**Comment by marccarre** [comment]
@floscha, I'll come up with a PR soon 🙂

**Comment by floscha** [comment]
Awesome! This looks like a great feature for people using Tinycards for some serious language learning 🙂
