### ISSUE TITLE
Improvement: nicer API when adding multiple facts on the back of cards

### ISSUE THREAD

**Issue by marccarre** [floscha/tinycards-python-api#51]
**Why?**

One may want to create cards with more than two facts, i.e. not just "front" and "back", but several "back" facts, like possible under the Tinycards UI. Currently, there isn't any "high-level" API covering this use-case, which forces one to do something along the lines of the below:

```python
cards = [...]  # source cards, containing multiple "fact" strings.
fields = set(['question', 'answer', 'sentence', '...'])  # the various fields for the multiple "facts" to support.
username, password = get_credentials()
tinycards = Tinycards(username, password)
user_id = tinycards.user_id
deck = Deck('Complex deck', user_id)
deck = tinycards.create_deck(deck)
for card in cards:
    front = Concept(fact=Fact(card.facts.pop('question')), user_id=user_id)
    front_side = Side(concepts=front, user_id=user_id)
    back = [Concept(fact=Fact(card.facts.pop('answer')), user_id=user_id)]
    back.extend([Concept(fact=card.facts[field], user_id=user_id) for field in fields if field in card.facts])
    back_side = Side(concepts=back, user_id=user_id)
    deck.cards.append(Card(front_side, back_side, user_id=user_id))
tinycards.update_deck(deck)
```
N.B.: this also happens not to be documented anywhere at the moment, unlike the simple case of two facts per card documented here:
https://github.com/floscha/tinycards-python-api/blob/cf8f5fc08fb3d5746719eb91c3c6fad8bdadecaa/examples/csv_to_deck.py#L10-L33

**How?**

Either relax the validation done in:
https://github.com/floscha/tinycards-python-api/blob/cf8f5fc08fb3d5746719eb91c3c6fad8bdadecaa/tinycards/model/deck.py#L35-L45
or (probably better), have `add_card` handle the aforementioned complexity when multiple facts are provided, with appropriate validation.

**Comment by floscha** [comment]
Good point. I wasn't even aware that a card could have up to three concepts on the back. So thanks for pointing it out! 🙂

Another thing I was wondering though: Why are you always passing the *user_id* as an argument? The Tinycards server should automatically set this to the *user_id* of your logged-in user once you call `tinycards.update_deck(deck)`.

**Comment by marccarre** [comment]
> Why are you always passing the user_id as an argument?

Because I saw most `__init__` methods ask for it, and I wasn't sure how it would be used behind the scene at the time I wrote the above, purely to see how far I could go 🙂 .

I only realised later that these arguments are only used when deserialising objects received from Tinycards' API, but haven't taken the time to clean this up yet, hence the above.

---- 

For reference, the `__init__` methods I'm referring to:

https://github.com/floscha/tinycards-python-api/blob/3e2e4af42ac5b9b2d3abf3c1a4269775fa1ac39b/tinycards/model/card.py#L24
https://github.com/floscha/tinycards-python-api/blob/3e2e4af42ac5b9b2d3abf3c1a4269775fa1ac39b/tinycards/model/concept.py#L10
https://github.com/floscha/tinycards-python-api/blob/3e2e4af42ac5b9b2d3abf3c1a4269775fa1ac39b/tinycards/model/side.py#L10

----

Unrelated to this issue per-se, but since we're discussing `user_id`s, note that `Deck` doesn't have an `user_id` argument to its constructor, even though the Tinycards API _does_ return such a field in the Deck JSON object, but has an `user_id` attribute initialised to `None`:
https://github.com/floscha/tinycards-python-api/blob/3e2e4af42ac5b9b2d3abf3c1a4269775fa1ac39b/tinycards/model/deck.py#L20

This attribute is never set by the JSON converter upon deserialisation.
However, it _is_ set in `update_deck`:
https://github.com/floscha/tinycards-python-api/blob/3e2e4af42ac5b9b2d3abf3c1a4269775fa1ac39b/tinycards/networking/rest_api.py#L218

Depending on how deck creation, update and cards additions are interleaved, it looks like `Card`s' `user_id` could be blanked out:
https://github.com/floscha/tinycards-python-api/blob/3e2e4af42ac5b9b2d3abf3c1a4269775fa1ac39b/tinycards/model/deck.py#L35-L42

I'm not sure if all of this is intended, but I'm also not sure it matters for the Tinycards API at the end of the day anyway, so... 🤷‍♂️

**Comment by floscha** [comment]
I originally included the *user_id* because the Tinycards API includes it in most of the JSON objects like decks, cards, and concepts. But thanks to your comment I figured the Python API just passes `None` down to the `Concept` objects. Consequentially, removing the *user_id* from all Python models didn't seem to impact any of the tests. So once #49 is merged, I will create a PR to clean up this *user_id* mess 😉

**Comment by floscha** [comment]
Since Tinycards has been [disabled by Duolingo](https://support.duolingo.com/hc/en-us/articles/360043909772-UPDATE-Tinycards-Announcement) on September 1, 2020, this repository will no longer be maintained.
