### ISSUE TITLE
Include card image url in card JSON object

### ISSUE THREAD

**Issue by Evvn** [floscha/tinycards-python-api#73]
I've dumped a deck to JSON using the deck_to_json function, however the resulting cards in the deck only have the text for front/back included with no image information. Is there a way to source the images of each card as well? I know the Deck class contains this information when you print a deck from a users collection.

**Comment by floscha** [comment]
Since Tinycards has been [disabled by Duolingo](https://support.duolingo.com/hc/en-us/articles/360043909772-UPDATE-Tinycards-Announcement) on September 1, 2020, this repository will no longer be maintained.
